trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo Build and deploy your FastAPI application.
    # Add commands to build and deploy your FastAPI app on Windows.
  displayName: 'Build and deploy'

# Add more steps as needed for deployment or other tasks.
